### ISSUE TITLE
Unable to build with Qt5.4

### ISSUE THREAD

**Issue by a-andreyev** [AlexandrePTJ/mopiqy_desktop#1]
Archlinux x86_64, Qt 5.4.1-2:
Cannot find libmopiqy out of the box, added this lines at the end of `./src/src.pro`:
`include(find_libmopiqy.pri)`
After that compiling starts but fails with error:
> ../../src/mainwindow.cpp: In constructor «MainWindow::MainWindow(QWidget*)»:
../../src/mainwindow.cpp:30:43: error: «connected» is not the element of «Mopidy::MopidyClient»
     connect(mopiqyApp()->mopidyClient(), &MopidyClient::connected, this, &MainWindow::onClientConnected);
                                           ^
../../src/mainwindow.cpp: In «void MainWindow::onMenuFileQuitTriggered()»:
../../src/mainwindow.cpp:225:46: error: «connected» is not element of: «Mopidy::MopidyClient»
     disconnect(mopiqyApp()->mopidyClient(), &MopidyClient::connected, this, &MainWindow::onClientConnected);
                                              ^
Makefile:854: error: «mainwindow.o»

I suppose it's connected with WebSockets 5.4 somehow, but not sure (Got qt-websockets 5.4 installed)
